spring.application.name=enjambre

# ========== SERVIDOR ==========
server.port=${PORT:8080}

# ========== BASE DE DATOS ==========
spring.jpa.database=mysql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD}

# ========== CORREO CON BREVO API HTTP ==========
# Si no configuras la variable de entorno BREVO_API_KEY, se mantendrá vacía y la aplicación iniciará
# pero mostrará un error explicativo en la consola al intentar enviar un correo.
brevo.api.key=${BREVO_API_KEY}
brevo.email.from=${BREVO_EMAIL_FROM:countercito10@gmail.com}

# ========== THYMELEAF ==========
spring.thymeleaf.cache=false

# ========== MULTIPART (CARGA DE ARCHIVOS) ==========
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
